// examples/generated-react/Content.tsx
import React from 'react';
import { MyForm } from './MyForm';
import { Preview } from './Preview';

export function Content() {
  return (
    <section style={{

    }}>
      <div style="display:flex; flex-direction:column; gap:8px;">
      <MyForm />
      <Preview />
    </div>
    </section>
  );
}

// examples/generated-vue/Content.vue
<script setup lang="ts">
import MyForm from './MyForm.vue';
import Preview from './Preview.vue';
</script>

<template>
  <section class="Content">
    <div style="display:flex; flex-direction:column; gap:8px;">
      <MyForm />
      <Preview />
    </div>
  </section>
</template>

<style scoped>
.Content {

}
</style>
